### ISSUE TITLE
Correctly authenticating with API v1, but getting incorrect responses

### ISSUE THREAD

**Issue by thomasrussellmurphy** [dnsimple/hubot-dnsimple#1]
After successfully configuring the API username+key, calling `hubot check domain` returns domain availability for all sites, including `google.com` and `dnsimple.com`.

**Comment by weppos** [comment]
Can you post an example of the output you get, and the domain you checked?

**Comment by thomasrussellmurphy** [comment]
`hubot check domain google.com`
`Cybersquat that shit!`

Per expected from https://github.com/dnsimple/hubot-dnsimple/blob/master/src/dnsimple.coffee#L22

**Comment by weppos** [comment]
Can you please retry now? We had some connection issue with the registrar, I wonder if that caused the error.

**Comment by thomasrussellmurphy** [comment]
Well, the API correctly failed to authenticate before I set the API key to a correct value. Now, `google.com` still is incorrectly listed as available.

**Comment by weppos** [comment]
@thomasrussellmurphy Your account is currently not subscribed. Access to our API is limited to subscribed users only.

The request returns a 404, which is the same status code V1 uses to say that the domain is available.

**Comment by thomasrussellmurphy** [comment]
Well, that's a horribly ambiguous result from the API, but not related to this repository.

I see that [v2](https://developer.dnsimple.com/v2/#responses) corrects that by adding 402 to the list of expected API error responses. I'll be removing this script from my hubot instance.

**Comment by weppos** [comment]
> Well, that's a horribly ambiguous result from the API, but not related to this repository.

I totally agree, it was a poor decision to use 404. Mistakes happen.

In API v2 we fixed it an we return 200 whenever the response is successful, and we add information in the payload bout the availability of the domain.

We'll update this script to use API v2 ASAP. Feel free to provide a patch.

**Comment by thomasrussellmurphy** [comment]
I am not a current customer of dnsimple and someone (I can't remember who and don't feel like tracking back) thought that this would provide a convenient check for the registration status for domains with any user account. I was upgrading the hubot to remove dependency on `hubot-scripts` and thought that something was broken because the obvious test of `google.com` returned an incorrect result. The 404 status/"domain is available" result was disregarded until now because it was parsed as a valid API access. Thanks for the clarification and may API v2 prevent this issue in the future.
